// <auto-generated />
using System;
using Company_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250619174628_seedingTables")]
    partial class seedingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company_System.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Human Resources Department",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Information Technology Department",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Finance Department",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("Company_System.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 303011,
                            DeptId = 1,
                            Email = "ali@company.com",
                            JoinDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ali Ahmed",
                            Password = "Ali12345",
                            PhoneNumber = "01012345678",
                            Salary = 8000.00m
                        },
                        new
                        {
                            Id = 101011,
                            DeptId = 2,
                            Email = "mona@company.com",
                            JoinDate = new DateTime(2022, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mona Said",
                            Password = "Mona@123",
                            PhoneNumber = "01123456789",
                            Salary = 9500.00m
                        },
                        new
                        {
                            Id = 123456,
                            DeptId = 3,
                            Email = "hassan@company.com",
                            JoinDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hassan Omar",
                            Password = "Hassan789!",
                            PhoneNumber = "01234567890",
                            Salary = 11000.00m
                        },
                        new
                        {
                            Id = 8080,
                            DeptId = 1,
                            Email = "Sara@company.com",
                            JoinDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sara Youssef",
                            Password = "Sara@1234",
                            PhoneNumber = "01345678901",
                            Salary = 9000.00m
                        });
                });

            modelBuilder.Entity("Company_System.Models.Employee", b =>
                {
                    b.HasOne("Company_System.Models.Department", "department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("Company_System.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
